CREATE PROCEDURE find_prisoners_from_city
  @city_name NVARCHAR(40)
  AS
  BEGIN
    SELECT PRISONER.NAME AS IMIĘ,
      PRISONER.SECOND_NAME AS NAZWISKO,
      PRISONER.AGE AS WIEK,
      SENTENCE.SINCE AS OD,
      SENTENCE.DELINQUENCY AS PRZEWINIENIE
      FROM PRISONER, SENTENCE, CITY
      WHERE CITY.NAME LIKE @city_name
    AND CITY.ID = PRISONER.CITY_ID
    AND PRISONER.SENTENCE_ID = SENTENCE.ID
  END

  select * from PRISONER
  select * from CITY

  EXEC find_prisoners_from_city 'Barczewo'

  EXEC find_prisoner_with_deliquency 'Napad'

CREATE PROCEDURE find_prisoner_sentenced_before
  @since DATETIME
  AS
  BEGIN
     SELECT PRISONER.NAME AS IMIĘ,
      PRISONER.SECOND_NAME AS NAZWISKO,
      PRISONER.AGE AS WIEK,
      SENTENCE.SINCE AS OD,
      SENTENCE.TILL AS DO,
      SENTENCE.DELINQUENCY AS PRZEWINIENIE
      FROM PRISONER, SENTENCE, CITY
      WHERE DATEDIFF(YEAR, @since, SENTENCE.SINCE) < 0
    AND CITY.ID = PRISONER.CITY_ID
    AND PRISONER.SENTENCE_ID = SENTENCE.ID

  END

  EXEC find_prisoner_sentenced_before '1999-12-2'

CREATE PROCEDURE find_prisoners_free_before
    @till DATETIME
    AS
  BEGIN
     SELECT PRISONER.NAME AS IMIĘ,
      PRISONER.SECOND_NAME AS NAZWISKO,
      PRISONER.AGE AS WIEK,
      SENTENCE.SINCE AS OD,
      SENTENCE.TILL AS DO,
      SENTENCE.DELINQUENCY AS PRZEWINIENIE
      FROM PRISONER, SENTENCE, CITY
      WHERE DATEDIFF(YEAR, @till, SENTENCE.TILL) < 0
    AND CITY.ID = PRISONER.CITY_ID
    AND PRISONER.SENTENCE_ID = SENTENCE.ID
    AND SENTENCE.TILL IS NOT NULL


  END

  drop procedure find_prisoners_free_before

  select * from prisoner

  EXEC find_prisoners_free_before '2019-01-20'