CREATE TABLE PROVINCE
(
 TERYT INT NOT NULL PRIMARY KEY,
 NAME NVARCHAR(40) NOT NULL
)
CREATE TABLE CITY
(
 ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 NAME NVARCHAR(40) NOT NULL ,
 PROVINCE_ID INT NOT NULL FOREIGN KEY REFERENCES PROVINCE(TERYT)
)
CREATE TABLE PRISON
(
 ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
 NAME NVARCHAR(40) NOT NULL ,
 NUMBER_OF_PRISONER INT,
 CITY_ID INT FOREIGN KEY REFERENCES CITY(ID)
)
CREATE TABLE SENTENCE
(
 ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
 DELINQUENCY NVARCHAR(255) NOT NULL ,
 SINCE DATETIME NOT NULL,
 TILL DATETIME,
 PRISON_ID INT FOREIGN KEY REFERENCES PRISON(ID)
)
CREATE TABLE PRISONER
(
   PESEL NVARCHAR(11) NOT NULL PRIMARY KEY ,
 NAME NVARCHAR(255) NOT NULL,
 AGE INT NOT NULL,
 NUMBER_OF_CRIMES INT,
 SEX NVARCHAR(1) NOT NULL,
 SECOND_NAME NVARCHAR(255) NOT NULL,
 SENTENCE_ID INT FOREIGN KEY REFERENCES SENTENCE(ID),
 CITY_ID INT NOT NULL FOREIGN KEY REFERENCES CITY(ID)
)
CREATE TABLE CELL
(
 ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
 RESIDORS_LIMIT INT NOT NULL,
 CURRENT_RESIDORS_NUMBER INT NOT NULL,
 PRISON_ID INT NOT NULL FOREIGN KEY REFERENCES PRISON(ID)
)
CREATE TABLE ACCOMMODATION
(
 ACCOMMODATION_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
 SINCE DATETIME NOT NULL ,
 TILL DATETIME NOT NULL ,
 PRISONER_ID NVARCHAR(11) NOT NULL FOREIGN KEY REFERENCES PRISONER(PESEL),
 CELL_ID INT NOT NULL FOREIGN KEY REFERENCES CELL(ID)
)
CREATE TABLE INCIDENT
(
 INCIDENT_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
 SHORT_DESCRIPTION NVARCHAR(255),
 TIME_OF_INCIDENT DATETIME,
 PRISONER_ID NVARCHAR(11) NOT NULL FOREIGN KEY REFERENCES PRISONER(PESEL),
 CELL_ID INT NOT NULL FOREIGN KEY REFERENCES CELL(ID)
)
